# Generated by Django 5.2.17 on 2026-09-24 23:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('ministry', models.CharField(blank=True, max_length=150, null=True)),
                ('team', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DEACTIVATED', 'Deactivated')], db_index=True, default='ACTIVE', max_length=30)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberMergeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('source_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_requests_as_source', to='members.member')),
                ('target_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_requests_as_target', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Merge Request',
                'verbose_name_plural': 'Member Merge Requests',
                'db_table': 'member_merge_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryContributor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=200, null=True)),
                ('provider_account_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('UNDER_REVIEW', 'Under Review'), ('LINKED', 'Linked'), ('CONVERTED', 'Converted')], db_index=True, default='UNVERIFIED', max_length=30)),
                ('converted_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_temporary', to='members.member')),
            ],
            options={
                'verbose_name': 'Temporary Contributor',
                'verbose_name_plural': 'Temporary Contributors',
                'db_table': 'temporary_contributors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberPhoneNumber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Phone Number',
                'verbose_name_plural': 'Member Phone Numbers',
                'db_table': 'member_phone_numbers',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('phone_number',), name='unique_active_phone_across_members'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('member',), name='unique_active_primary_phone_per_member')],
            },
        ),
    ]
