# Generated by Django 5.2.17 on 2026-09-25 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRecoverySession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=128, unique=True)),
                ('email_otp_hash', models.CharField(max_length=128)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_otp_hash', models.CharField(max_length=128)),
                ('phone_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admin_recovery_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
