# Generated by Django 5.2.17 on 2026-09-30 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-contribution_date', '-created_at'], 'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
