import csv
import io
import openpyxl
from django.db.models import QuerySet
from apps.contributions.models import Contribution
from apps.receipts.models import Receipt
from apps.requisitions.models import Requisition
from apps.members.models import Member
from apps.audit.models import AuditLog


class ReportService:
    """Reporting service generating dataset extracts and CSV/Excel exports."""

    @classmethod
    def export_to_csv(cls, headers: list[str], rows: list[list]) -> str:
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(headers)
        for row in rows:
            writer.writerow(row)
        return output.getvalue()

    @classmethod
    def export_to_excel(cls, headers: list[str], rows: list[list], sheet_title: str = "Report") -> bytes:
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = sheet_title
        ws.append(headers)
        for row in rows:
            ws.append([str(c) if c is not None else "" for c in row])
        output = io.BytesIO()
        wb.save(output)
        return output.getvalue()

    @classmethod
    def generate_contribution_report(cls, queryset: QuerySet[Contribution] | None = None) -> tuple[list[str], list[list]]:
        qs = queryset if queryset is not None else Contribution.objects.select_related("member", "temporary_contributor", "contribution_type", "recorded_by").all()
        headers = [
            "Contribution ID",
            "Receipt Number",
            "Contributor",
            "Type",
            "Amount",
            "Currency",
            "Payment Mode",
            "Entry Method",
            "Date",
            "Reference",
            "Status",
            "Recorded By",
        ]
        rows = []
        for c in qs:
            receipt_num = c.receipt.receipt_number if hasattr(c, "receipt") else "N/A"
            contributor = c.member.full_name if c.member else (str(c.temporary_contributor) if c.temporary_contributor else "Unknown")
            recorded = c.recorded_by.email if c.recorded_by else "System"
            rows.append([
                c.contribution_number,
                receipt_num,
                contributor,
                c.contribution_type.name,
                c.amount,
                c.currency,
                c.payment_mode,
                c.entry_method,
                c.created_at.strftime("%Y-%m-%d %H:%M"),
                c.reference_number or "",
                c.status,
                recorded,
            ])
        return headers, rows

    @classmethod
    def generate_receipt_report(cls, queryset: QuerySet[Receipt] | None = None) -> tuple[list[str], list[list]]:
        qs = queryset if queryset is not None else Receipt.all_objects.select_related("contribution", "generated_by_user").all()
        headers = [
            "Receipt Number",
            "Contribution ID",
            "Contributor",
            "Amount",
            "Currency",
            "Type",
            "Payment Mode",
            "Date",
            "Generated By",
            "Status",
        ]
        rows = []
        for r in qs:
            c = r.contribution
            contributor = c.member.full_name if c.member else (str(c.temporary_contributor) if c.temporary_contributor else "Unknown")
            gen_by = "System" if r.generated_by_system else (r.generated_by_user.email if r.generated_by_user else "Unknown")
            rows.append([
                r.receipt_number,
                c.contribution_number,
                contributor,
                c.amount,
                c.currency,
                c.contribution_type.name,
                c.payment_mode,
                r.generated_at.strftime("%Y-%m-%d %H:%M"),
                gen_by,
                r.status,
            ])
        return headers, rows

    @classmethod
    def generate_requisition_report(cls, queryset: QuerySet[Requisition] | None = None) -> tuple[list[str], list[list]]:
        qs = queryset if queryset is not None else Requisition.objects.all()
        headers = [
            "Requisition ID",
            "Requester",
            "Phone",
            "Ministry/Dept",
            "Purpose",
            "Requested Amount",
            "Approved Amount",
            "Disbursed Amount",
            "Preferred Method",
            "Status",
            "Date Needed",
            "Created At",
        ]
        rows = []
        for req in qs:
            org = req.department or req.ministry or req.team or req.group_name or ""
            rows.append([
                req.requisition_number,
                req.requester_name,
                req.requester_phone,
                org,
                req.purpose,
                req.amount_requested,
                req.approved_amount or "N/A",
                req.disbursed_amount,
                req.preferred_disbursement_method or "",
                req.status,
                str(req.date_funds_needed or ""),
                req.created_at.strftime("%Y-%m-%d %H:%M"),
            ])
        return headers, rows
