# Generated by Django 5.2.17 on 2026-09-24 23:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Receipt number must strictly follow the format HLC- followed by exactly 7 digits (e.g., HLC-5831047).', regex='^HLC-\\d{7}$')])),
                ('generated_by_system', models.BooleanField(default=False)),
                ('pdf_storage_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='contributions.contribution')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_deleted', to=settings.AUTH_USER_MODEL)),
                ('generated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'receipts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptDeliveryRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('channel', models.CharField(default='SMS', max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('secure_link', models.TextField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='receipts.receipt')),
            ],
            options={
                'verbose_name': 'Receipt Delivery Record',
                'verbose_name_plural': 'Receipt Delivery Records',
                'db_table': 'receipt_delivery_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptEdit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='receipts.receipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_edits_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Edit',
                'verbose_name_plural': 'Receipt Edits',
                'db_table': 'receipt_edits',
                'ordering': ['-created_at'],
            },
        ),
    ]
