# Generated by Django 5.2.17 on 2026-10-02 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_alter_contribution_options_and_more'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptGenerationAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_generation_attempts', to='contributions.contribution')),
            ],
            options={
                'verbose_name': 'Receipt Generation Attempt',
                'verbose_name_plural': 'Receipt Generation Attempts',
                'db_table': 'receipt_generation_attempts',
                'ordering': ['attempt_number'],
            },
        ),
    ]
