from django.core.management.base import BaseCommand
from django.conf import settings
from django.db import transaction
from apps.accounts.models import User, Role, Permission, UserRole, RolePermission
from apps.contributions.models import ContributionType
from apps.notifications.models import NotificationTemplate, NotificationType


class Command(BaseCommand):
    help = "Idempotently seeds database with initial roles, permissions, contribution types, templates, and the single System Administrator."

    @transaction.atomic
    def handle(self, *args, **options):
        self.stdout.write("Starting idempotent database seeding...")

        # 1. Seed Roles
        admin_role, _ = Role.objects.get_or_create(
            name=Role.SYSTEM_ADMINISTRATOR,
            defaults={"description": "Highest-level application user with system-wide review and administrative access."}
        )
        # System User is an application user type, not a selectable role.
        # Deactivate the legacy role if it exists from an earlier implementation.
        legacy_system_user_role = Role.objects.filter(name=Role.SYSTEM_USER).first()
        if legacy_system_user_role:
            legacy_system_user_role.is_active = False
            legacy_system_user_role.save(update_fields=["is_active", "updated_at"])
        self.stdout.write(self.style.SUCCESS("✓ Protected administrator role seeded; custom user roles remain administrator-managed"))

        # 2. Seed Permissions
        permissions_data = [
            ("contribution.create", "Create Contribution", "Record manual contributions"),
            ("contribution.edit_own", "Edit Own Contribution", "Edit own manual contributions"),
            ("contribution.delete_own", "Delete Own Contribution", "Delete own manual contributions"),
            ("receipt.view_own", "View Own Receipt", "View receipts generated by user"),
            ("receipt.edit_own", "Edit Own Receipt", "Edit own manual receipts"),
            ("receipt.delete_own", "Delete Own Receipt", "Soft delete own manual receipts"),
            ("member.create", "Create Member", "Register new church members"),
            ("member.edit", "Edit Member", "Update existing member details"),
            ("member.merge.request", "Request Member Merge", "Initiate a member merge request"),
            ("member.merge.approve", "Approve Member Merge", "Authorize or reject member merge requests"),
            ("requisition.view", "View Requisitions", "View requisitions in queue"),
            ("requisition.review", "Review Requisitions", "Start working and review requisitions"),
            ("requisition.approve", "Approve Requisitions", "Approve or reject requisitions"),
            ("requisition.disburse", "Disburse Requisitions", "Process and disburse approved funds"),
            ("evidence.verify", "Verify Evidence", "Review and verify post-disbursement evidence"),
            ("report.view", "View Reports", "Access financial and administrative reports"),
            ("report.export", "Export Reports", "Download CSV, Excel, or PDF reports"),
            ("user.manage", "Manage Users", "Create and deactivate internal system users"),
            ("audit.view", "View Audit Logs", "Inspect immutable system audit trails"),
        ]

        created_perms = {}
        for code, name, desc in permissions_data:
            perm, _ = Permission.objects.update_or_create(
                code=code,
                defaults={"name": name, "description": desc}
            )
            created_perms[code] = perm
        self.stdout.write(self.style.SUCCESS("✓ Permissions seeded"))

        # System User permissions are intentionally not seeded here.
        # The System Administrator creates custom roles and selects the permissions for each role.

        # Legacy compatibility: remove any persisted Django staff/admin flags.
        User.objects.filter(is_staff=True).update(is_staff=False)

        # 3. Seed Contribution Types
        types_data = [
            ("Tithe", "Scriptural tenth contribution of income or earnings"),
            ("Thanksgiving", "Special thank-offering"),
            ("Higher Life Partners", "Regular partnership giving for ministry arms"),
            ("Building Project", "Contributions designated for church physical development"),
            ("Other", "Special collections, appeals, or unspecified contributions"),
        ]
        seed_types = {}
        for name, desc in types_data:
            c_type, _ = ContributionType.objects.update_or_create(
                name=name,
                defaults={"description": desc, "is_active": True}
            )
            seed_types[name] = c_type
        self.stdout.write(self.style.SUCCESS("✓ Contribution types seeded"))

        # 4. Seed the Exactly One System Administrator
        admin_email = settings.SYSTEM_ADMIN_EMAIL
        admin_password = settings.SYSTEM_ADMIN_INITIAL_PASSWORD

        # Verify no other user holds System Administrator role
        existing_admin_assignment = UserRole.objects.filter(role=admin_role).first()
        if existing_admin_assignment:
            admin_user = existing_admin_assignment.user
            if admin_user.is_staff:
                admin_user.is_staff = False
                admin_user.save(update_fields=["is_staff"])
            self.stdout.write(f"Existing System Administrator found: {admin_user.email}")
        else:
            admin_user, created = User.objects.get_or_create(
                email=admin_email,
                defaults={
                    "first_name": "System",
                    "last_name": "Administrator",
                    "is_active": True,
                    "is_staff": False,
                }
            )
            if created:
                admin_user.set_password(admin_password)
                admin_user.save()
            UserRole.objects.get_or_create(user=admin_user, role=admin_role)
            self.stdout.write(self.style.SUCCESS(f"✓ Initial System Administrator created: {admin_email}"))

        # 5. Seed Notification Templates
        templates_data = [
            (
                "Receipt Delivery SMS",
                NotificationType.RECEIPT,
                None,
                "Dear {first_name}, thank you for your contribution of {amount} {currency} ({contribution_type}) to TCI Higher Life Center on {date}. Your official receipt is {receipt_number}. View/download receipt: {secure_link}"
            ),
            (
                "Tithe Thank You",
                NotificationType.THANK_YOU,
                seed_types.get("Tithe"),
                "Dear {first_name}, thank you for honoring God with your Tithe of {amount} {currency}. The Lord open the windows of heaven and pour you out a blessing! — TCI Higher Life Center"
            ),
            (
                "Thanksgiving Thank You",
                NotificationType.THANK_YOU,
                seed_types.get("Thanksgiving"),
                "Dear {first_name}, thank you for your Thanksgiving offering of {amount} {currency}. May your life continuously overflow with praise and divine favor! — TCI Higher Life Center"
            ),
            (
                "Higher Life Partners Thank You",
                NotificationType.THANK_YOU,
                seed_types.get("Higher Life Partners"),
                "Dear {first_name}, thank you for partnering with Higher Life Center with your gift of {amount} {currency}. Together, we impact lives and expand the Kingdom! — TCI Higher Life Center"
            ),
            (
                "Building Project Thank You",
                NotificationType.THANK_YOU,
                seed_types.get("Building Project"),
                "Dear {first_name}, thank you for building the House of the Lord with your contribution of {amount} {currency}. God establish and prosper you! — TCI Higher Life Center"
            ),
            (
                "General Contribution Thank You",
                NotificationType.THANK_YOU,
                None,
                "Dear {first_name}, thank you for your generous gift of {amount} {currency} to TCI Higher Life Center. God bless you abundantly!"
            ),
        ]

        for name, n_type, c_type, body in templates_data:
            NotificationTemplate.objects.update_or_create(
                name=name,
                defaults={
                    "notification_type": n_type,
                    "contribution_type": c_type,
                    "template_body": body,
                    "is_active": True,
                    "created_by": admin_user,
                }
            )
        self.stdout.write(self.style.SUCCESS("✓ Notification templates seeded"))
        self.stdout.write(self.style.SUCCESS("Database seeding completed successfully."))
