import re
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.conf import settings
from django.utils import timezone
from apps.core.models import UUIDBaseModel, TimeStampedModel
from apps.contributions.models import Contribution
from apps.core.services.id_generator import IdGenerator


class ReceiptStatus(models.TextChoices):
    ACTIVE = "ACTIVE", "Active"
    DELETED = "DELETED", "Deleted"


class ReceiptQuerySet(models.QuerySet):
    """QuerySet that blocks bulk physical deletion of receipts."""
    def delete(self):
        raise ValidationError("Receipt records cannot be physically deleted to preserve financial audit trail. Use soft_delete() for manual receipts.")


class ActiveReceiptManager(models.Manager.from_queryset(ReceiptQuerySet)):
    """Returns only active, non-soft-deleted receipts."""
    def get_queryset(self):
        return super().get_queryset().filter(status=ReceiptStatus.ACTIVE)


class AllReceiptsManager(models.Manager.from_queryset(ReceiptQuerySet)):
    """Returns all receipts, including soft-deleted ones."""
    pass


class Receipt(UUIDBaseModel):
    """
    Receipt record tied one-to-one with a Contribution.
    Enforces format HLC-XXXXXXX (strictly 7 digits).
    Table: receipts
    """
    RECEIPT_REGEX = r"^HLC-\d{7}$"
    receipt_validator = RegexValidator(
        regex=RECEIPT_REGEX,
        message="Receipt number must strictly follow the format HLC- followed by exactly 7 digits (e.g., HLC-5831047)."
    )

    receipt_number = models.CharField(
        max_length=20,
        unique=True,
        db_index=True,
        validators=[receipt_validator]
    )
    contribution = models.OneToOneField(
        Contribution,
        on_delete=models.PROTECT,
        related_name="receipt"
    )
    generated_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="receipts_generated"
    )
    generated_by_system = models.BooleanField(default=False)
    pdf_storage_key = models.CharField(max_length=500)
    status = models.CharField(
        max_length=20,
        choices=ReceiptStatus.choices,
        default=ReceiptStatus.ACTIVE,
        db_index=True
    )
    generated_at = models.DateTimeField(default=timezone.now)
    deleted_at = models.DateTimeField(null=True, blank=True)
    deleted_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="receipts_deleted"
    )

    # Standard manager returns active receipts; all_objects includes soft-deleted
    objects = ActiveReceiptManager()
    all_objects = AllReceiptsManager()

    class Meta:
        db_table = "receipts"
        verbose_name = "Receipt"
        verbose_name_plural = "Receipts"
        ordering = ["-generated_at"]

    def clean(self):
        # Format check
        if self.receipt_number and not re.match(self.RECEIPT_REGEX, self.receipt_number):
            raise ValidationError(f"Receipt number {self.receipt_number} does not match HLC-XXXXXXX (7 digits).")

        # Automatic receipt immutability check
        if self.pk and not self._state.adding:
            original = Receipt.all_objects.filter(pk=self.pk).first()
            if original and original.generated_by_system:
                # If generated by system, changes to financial fields, metadata, or status are prohibited
                if (
                    self.receipt_number != original.receipt_number or
                    self.contribution_id != original.contribution_id or
                    self.generated_by_system != original.generated_by_system or
                    self.pdf_storage_key != original.pdf_storage_key or
                    self.status != original.status
                ):
                    raise ValidationError("Automatic receipts are finalized and immutable. Normal modifications are strictly prohibited.")

    def soft_delete(self, user):
        """Soft-deletes manual receipt. Automatic receipts cannot be deleted."""
        if self.generated_by_system:
            raise ValidationError("Automatic receipts are immutable and cannot be deleted.")
        self.status = ReceiptStatus.DELETED
        self.deleted_at = timezone.now()
        self.deleted_by = user
        self.save(update_fields=["status", "deleted_at", "deleted_by", "updated_at"])

    def delete(self, *args, **kwargs):
        raise ValidationError("Receipt records cannot be physically deleted to preserve financial audit trail. Use soft_delete() for manual receipts.")

    def save(self, *args, **kwargs):
        if not self.receipt_number:
            self.receipt_number = IdGenerator.generate_receipt_number()
        self.full_clean()
        super().save(*args, **kwargs)

    @property
    def contributor_name(self) -> str:
        """
        Returns contributor display name.
        Contributor phone numbers must NEVER appear on the receipt.
        """
        if self.contribution.member:
            return self.contribution.member.full_name
        elif self.contribution.temporary_contributor:
            tc = self.contribution.temporary_contributor
            parts = [tc.first_name, tc.last_name]
            full = " ".join([p for p in parts if p]).strip()
            if full:
                return full
            if tc.provider_name:
                return tc.provider_name
            return "Temporary Contributor"
        return "Church Contributor"

    @property
    def generated_by_display(self) -> str:
        if self.generated_by_system:
            return "HLC/System"
        if self.generated_by_user:
            name = self.generated_by_user.full_name
            if name:
                return f"{name} (System User)"
            return f"{self.generated_by_user.email} (System User)"
        return "System User"

    @property
    def is_deleted(self) -> bool:
        return self.status == ReceiptStatus.DELETED

    @property
    def is_manual(self) -> bool:
        return not self.generated_by_system

    def __str__(self):
        return f"{self.receipt_number} ({self.contribution.contribution_number})"


class ReceiptEdit(UUIDBaseModel):
    """
    Audit log of field-level manual receipt edits.
    Table: receipt_edits
    """
    receipt = models.ForeignKey(Receipt, on_delete=models.CASCADE, related_name="edits")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="receipt_edits_made")
    field_name = models.CharField(max_length=100)
    old_value = models.TextField(null=True, blank=True)
    new_value = models.TextField(null=True, blank=True)
    reason = models.TextField()

    class Meta:
        db_table = "receipt_edits"
        verbose_name = "Receipt Edit"
        verbose_name_plural = "Receipt Edits"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.receipt.receipt_number} edit on {self.field_name} by {self.user}"


class ReceiptDeliveryRecord(UUIDBaseModel):
    """
    Tracks receipt SMS delivery attempts.
    Table: receipt_delivery_records
    """
    receipt = models.ForeignKey(Receipt, on_delete=models.CASCADE, related_name="deliveries")
    recipient_phone = models.CharField(max_length=30)
    channel = models.CharField(max_length=20, default="SMS")
    status = models.CharField(max_length=30, default="PENDING")
    secure_link = models.TextField(null=True, blank=True)
    provider_reference = models.CharField(max_length=200, null=True, blank=True)
    attempt_count = models.IntegerField(default=0)
    last_attempt_at = models.DateTimeField(null=True, blank=True)
    delivered_at = models.DateTimeField(null=True, blank=True)
    failure_reason = models.TextField(null=True, blank=True)

    class Meta:
        db_table = "receipt_delivery_records"
        verbose_name = "Receipt Delivery Record"
        verbose_name_plural = "Receipt Delivery Records"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.receipt.receipt_number} -> {self.recipient_phone} ({self.status})"
