# Generated by Django 5.2.17 on 2026-09-24 23:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('PROVIDER', 'Provider')], default='USER', max_length=20)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial')], default='SUCCESS', max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx')],
            },
        ),
    ]
