# Generated by Django 5.2.17 on 2026-09-24 23:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('requester_name', models.CharField(max_length=200)),
                ('requester_phone', models.CharField(db_index=True, max_length=30)),
                ('ministry', models.CharField(blank=True, max_length=150, null=True)),
                ('team', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('group_name', models.CharField(blank=True, max_length=150, null=True)),
                ('purpose', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_funds_needed', models.DateField(blank=True, null=True)),
                ('preferred_disbursement_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('preferred_disbursement_details', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING_DISBURSEMENT', 'Pending Disbursement'), ('DISBURSED', 'Disbursed'), ('EVIDENCE_SUBMITTED', 'Evidence Submitted'), ('UNDER_VERIFICATION', 'Under Verification'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('related_requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='requisitions.requisition')),
                ('requester_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='members.member')),
            ],
            options={
                'verbose_name': 'Requisition',
                'verbose_name_plural': 'Requisitions',
                'db_table': 'requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='requisitions.requisition')),
            ],
            options={
                'verbose_name': 'Requisition Approval',
                'verbose_name_plural': 'Requisition Approvals',
                'db_table': 'requisition_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_granted', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requisitions', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='requisitions.requisition')),
            ],
            options={
                'verbose_name': 'Requisition Assignment',
                'verbose_name_plural': 'Requisition Assignments',
                'db_table': 'requisition_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_name', models.CharField(max_length=200)),
                ('uploader_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('storage_key', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requisitions.requisition')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisition Attachment',
                'verbose_name_plural': 'Requisition Attachments',
                'db_table': 'requisition_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionDisbursement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=30)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('disbursed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements_processed', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='requisitions.requisition')),
            ],
            options={
                'verbose_name': 'Requisition Disbursement',
                'verbose_name_plural': 'Requisition Disbursements',
                'db_table': 'requisition_disbursements',
                'ordering': ['-disbursed_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionEvidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_name', models.CharField(max_length=200)),
                ('uploader_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('storage_key', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='UPLOADED', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='requisitions.requisition')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_reviews_performed', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_evidence_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisition Evidence',
                'verbose_name_plural': 'Requisition Evidence Files',
                'db_table': 'requisition_evidence',
                'ordering': ['-created_at'],
            },
        ),
    ]
