# Generated by Django 5.2.17 on 2026-09-24 23:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('THANK_YOU', 'Thank You'), ('RECEIPT', 'Receipt'), ('PAYMENT_FAILURE', 'Payment Failure'), ('REQUISITION_APPROVED', 'Requisition Approved'), ('REQUISITION_REJECTED', 'Requisition Rejected'), ('READY_FOR_DISBURSEMENT', 'Ready for Disbursement'), ('PROOF_UPLOAD', 'Proof Upload Request'), ('EVIDENCE_REJECTED', 'Evidence Rejected'), ('RECEIPT_GENERATION_FAILED', 'Receipt Generation Failed'), ('THANK_YOU_FAILED', 'Thank You Failed'), ('MERCHANT_TRANSACTION', 'Merchant Transaction'), ('DUPLICATE_TRANSACTION', 'Duplicate Transaction'), ('OTHER', 'Other')], max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_phone', models.CharField(db_index=True, max_length=30)),
                ('related_record_type', models.CharField(max_length=100)),
                ('related_record_id', models.UUIDField()),
                ('channel', models.CharField(default='SMS', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('MANUAL_ACTION_REQUIRED', 'Manual Action Required')], db_index=True, default='PENDING', max_length=30)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('RECEIPT_GENERATION_FAILED', 'Receipt Generation Failed'), ('THANK_YOU_NOTIFICATION_FAILED', 'Thank You Notification Failed'), ('MERCHANT_TRANSACTION', 'Merchant Transaction'), ('DUPLICATE_TRANSACTION_REVIEW', 'Duplicate Transaction Review'), ('UNKNOWN_CONTRIBUTOR_REVIEW', 'Unknown Contributor Review'), ('OTHER', 'Other')], max_length=100)),
                ('related_record_type', models.CharField(max_length=100)),
                ('related_record_id', models.UUIDField()),
                ('description', models.TextField()),
                ('attempt_count', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=30)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_actions_assigned', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_actions_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Action',
                'verbose_name_plural': 'Manual Actions',
                'db_table': 'manual_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField()),
                ('provider_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Attempt',
                'verbose_name_plural': 'Notification Attempts',
                'db_table': 'notification_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('notification_type', models.CharField(choices=[('THANK_YOU', 'Thank You'), ('RECEIPT', 'Receipt'), ('PAYMENT_FAILURE', 'Payment Failure'), ('REQUISITION_APPROVED', 'Requisition Approved'), ('REQUISITION_REJECTED', 'Requisition Rejected'), ('READY_FOR_DISBURSEMENT', 'Ready for Disbursement'), ('PROOF_UPLOAD', 'Proof Upload Request'), ('EVIDENCE_REJECTED', 'Evidence Rejected'), ('RECEIPT_GENERATION_FAILED', 'Receipt Generation Failed'), ('THANK_YOU_FAILED', 'Thank You Failed'), ('MERCHANT_TRANSACTION', 'Merchant Transaction'), ('DUPLICATE_TRANSACTION', 'Duplicate Transaction'), ('OTHER', 'Other')], max_length=50)),
                ('template_body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('contribution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates', to='contributions.contributiontype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate'),
        ),
    ]
