# Generated by Django 5.2.17 on 2026-10-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('THANK_YOU', 'Thank You'), ('RECEIPT', 'Receipt'), ('PAYMENT_FAILURE', 'Payment Failure'), ('REQUISITION_APPROVED', 'Requisition Approved'), ('REQUISITION_REJECTED', 'Requisition Rejected'), ('READY_FOR_DISBURSEMENT', 'Ready for Disbursement'), ('PROOF_UPLOAD', 'Proof Upload Request'), ('EVIDENCE_REJECTED', 'Evidence Rejected'), ('RECEIPT_GENERATION_FAILED', 'Receipt Generation Failed'), ('THANK_YOU_FAILED', 'Thank You Failed'), ('FAILED_NOTIFICATION', 'Failed Notification'), ('MERCHANT_TRANSACTION', 'Merchant Transaction'), ('DUPLICATE_TRANSACTION', 'Duplicate Transaction'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('MANUAL_ACTION_REQUIRED', 'Manual Action Required')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_record_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_record_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manualaction',
            name='related_record_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualaction',
            name='related_record_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('THANK_YOU', 'Thank You'), ('RECEIPT', 'Receipt'), ('PAYMENT_FAILURE', 'Payment Failure'), ('REQUISITION_APPROVED', 'Requisition Approved'), ('REQUISITION_REJECTED', 'Requisition Rejected'), ('READY_FOR_DISBURSEMENT', 'Ready for Disbursement'), ('PROOF_UPLOAD', 'Proof Upload Request'), ('EVIDENCE_REJECTED', 'Evidence Rejected'), ('RECEIPT_GENERATION_FAILED', 'Receipt Generation Failed'), ('THANK_YOU_FAILED', 'Thank You Failed'), ('FAILED_NOTIFICATION', 'Failed Notification'), ('MERCHANT_TRANSACTION', 'Merchant Transaction'), ('DUPLICATE_TRANSACTION', 'Duplicate Transaction'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
